chef_workflow_task 'chef_server'
chef_workflow_task 'chef/cookbooks/upload'
chef_workflow_task 'chef/upload'
chef_workflow_task 'chef/clean'
chef_workflow_task 'chef/build'
chef_workflow_task 'chef/converge'
chef_workflow_task 'chef/info'
chef_workflow_task 'test/build'
